### ISSUE TITLE
Subscribe to Specific topics with conditional parameters

### ISSUE THREAD

**Issue by Saad-ISAA** [larsonnn/strapi-plugin-socket.io#1]
Currently all the front-end client can receive data subscribed to CRUD topics from any collection/content type
All the data can be received,
where as, there are many use cases where all the records should not be passes to the front-end subscribers
instead a record should be passed which is relevant to a user/front-end subscriber only.
For example - Notifications
if a record is inserted in the Notifications collection, then only that specific user/receiver should be able to receive that record on his subscription on front-end.
Notifications can be a broadcast (send to all) (works in the current scenario of the plugin),
Notification can be user specific only (received by only a specific user)

This Notification is just an example to understand the requirement. there are and can be many other similar use cases

**Comment by x0ptr** [comment]
Great Idea.

Im look forward to implement that soon. We have to consider that we need to change StrapIO too.

1. StrapIO needs to handle joining socket.io rooms
2. Plugin needs to handle this rooms

As first step I would implement basic subscribe mechanics to an collection-type. So the user needs to subscribe to a collection type before receiving data. But it will not handle further permissions or custom rooms.

I would set subscription mode as default. By setting it to false you have the behavior like now.

**Comment by Saad-ISAA** [comment]
alright, let's divide it into micro tasks, and maybe let's do it together....
socket.io is serving many use cases in strapi so we should make this plugin better...
I'll create another issue for feature request where we can add a screen on the admin panel, to control the allowed content types like check boxes on the web hooks page of admin panel.
user will be able to control which content types will be allowed for sockets.

**Comment by x0ptr** [comment]
I just updated strapio to version 2 and it is published.

you can now join rooms with `socket.emit('subscribe', 'article')` article is the content-type.

this should already works for the plugin because it works the same.

**Comment by Saad-ISAA** [comment]
alright that's great..... now you working on the issue ?
rooms will give the benefit of grouping users who receive the notification

**Comment by x0ptr** [comment]
Next step would be to subscribe to a specific entity like `socket.emit('subscribe', 'notification_#id`). And then its a solid plugin. The rest would be up to another plugin which controls permissions etc.

**Comment by Saad-ISAA** [comment]
this will be cool brother

**Comment by khalidzamer** [comment]
I 🧡 Internet

**Comment by x0ptr** [comment]
I have just updated strapio, you can now join specific entity rooms like `socket.emit('subscribe', 'article_4')` which would join the room for this specific article with id 4.

I will close this issue. For further development pls create a new one.
