### ISSUE TITLE
Support for Strapi v4

### ISSUE THREAD

**Issue by saintego** [larsonnn/strapi-plugin-socket.io#6]
Hi,
are you planning to support for strapi v4 with new plugins?

**Comment by x0ptr** [comment]
yes.

**Comment by x0ptr** [comment]
I just updated the folder structure for v4. There are some changes need to be done. With the next Version its ready for v4 only.

**Comment by x0ptr** [comment]
I just updated strapio and strapi-plugin-socket-io to version 3.0.0. It works with strapi v4 now. But only with v4!

**Comment by RaimonxDev** [comment]
When will you update the readme.md?, Thanks

**Comment by x0ptr** [comment]
README is updated. I close this issue.
