### ISSUE TITLE
npm package version

### ISSUE THREAD

**Issue by julientaq** [larsonnn/strapi-plugin-socket.io#7]
Hi there,

i have two Strapi setup for different project (one under strapi 3 and one under strapi 4, would be too easy if it was both version 4 :D) 

I’m not sure about what version of the plugin is on npm. It seems that it’s the 2.1.2 (which is strapi3). 
Is it possible to update npm with the latest? (or did i completely misread everything? )

Thanks a lot!

**Comment by x0ptr** [comment]
there is currently no support for strapi v4. Thats why npm has no version for that anymore.

**Comment by julientaq** [comment]
Oh ok!
I think that the readme needs an update because it says it work for v4.

Anyway, thanks for letting me know and have a great day!
